rule reversing_tool_process_name {
    meta:
        description = "Executable names of common reversing tools"
        author = "@larsborn"
        created_at = "2021-01-16"
        example_hash_01 = "8fbf21e9ecaa64b8f71904791380a3efa08f71f18f18fc9f7e171de2c5a946fc"

        DaysofYARA = "2/100"
    strings:
        $ = "ollydbg.exe"
        $ = "ProcessHacker.exe"
        $ = "tcpview.exe"
        $ = "autoruns.exe"
        $ = "autorunsc.exe"
        $ = "filemon.exe"
        $ = "procmon.exe"
        $ = "regmon.exe"
        $ = "procexp.exe"
        $ = "idaq.exe"
        $ = "idaq64.exe"
        $ = "ImmunityDebugger.exe"
        $ = "Wireshark.exe"
        $ = "dumpcap.exe"
        $ = "HookExplorer.exe"
        $ = "ImportREC.exe"
        $ = "PETools.exe"
        $ = "LordPE.exe"
        $ = "SysInspector.exe"
        $ = "proc_analyzer.exe"
        $ = "sysAnalyzer.exe"
        $ = "sniff_hit.exe"
        $ = "windbg.exe"
        $ = "joeboxcontrol.exe"
        $ = "joeboxserver.exe"
        $ = "joeboxserver.exe"
        $ = "ResourceHacker.exe"
        $ = "x32dbg.exe"
        $ = "x64dbg.exe"
        $ = "Fiddler.exe"
        $ = "httpdebugger.exe"
        $ = "SbieCtrl.exe"
        $ = "SbieSvc.exe"
        $ = "SandboxieDcomLaunch.exe"
        $ = "SandboxieRpcSs.exe"
    condition:
        any of them
}
